"""empty message

Revision ID: 18b514c1b30b
Revises: None
Create Date: 2015-02-21 15:58:10.807830

"""

# revision identifiers, used by Alembic.
revision = '18b514c1b30b'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
