"""empty message

Revision ID: 2636b770a11b
Revises: None
Create Date: 2015-02-21 14:12:51.450616

"""

# revision identifiers, used by Alembic.
revision = '2636b770a11b'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('url', 'clicks')
    op.drop_column('user', 'first_name')
    op.drop_column('user', 'last_name')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_name', sa.VARCHAR(length=50), server_default=sa.text(u"''::character varying"), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('first_name', sa.VARCHAR(length=50), server_default=sa.text(u"''::character varying"), autoincrement=False, nullable=False))
    op.add_column('url', sa.Column('clicks', sa.INTEGER(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
