"""empty message

Revision ID: 3f144068c090
Revises: None
Create Date: 2015-02-17 20:15:57.513970

"""

# revision identifiers, used by Alembic.
revision = '3f144068c090'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('url', sa.Column('clicks', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('url', 'clicks')
    ### end Alembic commands ###
